# Generated by Django 5.1.1 on 2024-10-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
